name: big-data-analytics-frytki
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - black=23.3.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.3
  - flake8=6.0.0
  - idna=3.4
  - intel-openmp=2023.1.0
  - isort=5.9.3
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mccabe=0.7.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openssl=3.0.11
  - packaging=23.1
  - pandas=2.1.1
  - pathspec=0.10.3
  - pip=23.3
  - platformdirs=3.10.0
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyflakes=3.0.1
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
